import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { ROUTES } from "@/lib/routes";
import { getSession } from "@/lib/api/auth/session";
import { SessionProvider } from "@/contexts/SessionContext";
import ResponsiveLayout from "@/components/layout/ResponsiveLayout";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getSession();

  if (!user) {
    redirect(ROUTES.LOGIN);
  }

  return (
    <SessionProvider user={user}>
      <ResponsiveLayout user={user}>{children}</ResponsiveLayout>
    </SessionProvider>
  );
}