import { Task } from "@/types/task";

export function getDummyProjectTasks(projectId: number): Task[] {
    return [
        {
            id: -101,
            title: "Riset kompetitor untuk fitur baru",
            description: "Bandingkan 3 aplikasi sejenis, catat fitur unggulan masing-masing",
            status: "unclaimed",
            priority: null,
            displayOrder: 0,
            projectId,
            deadline: "2026-08-25T00:00:00.000Z",
            assigneeId: null,
            createdBy: 1,
            isClaimable: true,
            createdAt: "2026-08-01T08:00:00.000Z",
            updatedAt: null,
        },
        {
            id: -102,
            title: "Tulis dokumentasi API auth",
            description: null,
            status: "unclaimed",
            priority: 2,
            displayOrder: 1,
            projectId,
            deadline: null,
            assigneeId: null,
            createdBy: 1,
            isClaimable: true,
            createdAt: "2026-08-02T08:00:00.000Z",
            updatedAt: null,
        },
        {
            id: -103,
            title: "Setup CI/CD pipeline",
            description: "Konfigurasi GitHub Actions untuk auto-deploy ke staging",
            status: "todo",
            priority: 1,
            displayOrder: 0,
            projectId,
            deadline: "2026-08-14T00:00:00.000Z",
            assigneeId: 2,
            createdBy: 1,
            isClaimable: false,
            createdAt: "2026-08-03T08:00:00.000Z",
            updatedAt: null,
        },
        {
            id: -104,
            title: "Desain wireframe halaman login",
            description: "Buat wireframe low-fidelity untuk alur login dan register",
            status: "ongoing",
            priority: 1,
            displayOrder: 0,
            projectId,
            deadline: "2026-08-13T00:00:00.000Z",
            assigneeId: 3,
            createdBy: 1,
            isClaimable: false,
            createdAt: "2026-08-01T08:30:00.000Z",
            updatedAt: "2026-08-09T10:00:00.000Z",
        },
        {
            id: -105,
            title: "Integrasi payment gateway",
            description: null,
            status: "ongoing",
            priority: 2,
            displayOrder: 1,
            projectId,
            deadline: "2026-08-11T00:00:00.000Z",
            assigneeId: 2,
            createdBy: 1,
            isClaimable: false,
            createdAt: "2026-08-04T08:00:00.000Z",
            updatedAt: null,
        },
        {
            id: -106,
            title: "Review PR integrasi payment gateway",
            description: null,
            status: "submitted",
            priority: 2,
            displayOrder: 0,
            projectId,
            deadline: "2026-08-20T00:00:00.000Z",
            assigneeId: 3,
            createdBy: 1,
            isClaimable: false,
            createdAt: "2026-08-06T09:00:00.000Z",
            updatedAt: "2026-08-10T11:00:00.000Z",
        },
        {
            id: -107,
            title: "Perbaiki bug validasi form onboarding",
            description: "User bisa lolos ke step 2 walau field wajib kosong",
            status: "in_revision",
            priority: 1,
            displayOrder: 1,
            projectId,
            deadline: "2026-08-09T00:00:00.000Z",
            assigneeId: 2,
            createdBy: 1,
            isClaimable: false,
            createdAt: "2026-07-20T10:00:00.000Z",
            updatedAt: "2026-08-08T15:30:00.000Z",
        },
        {
            id: -108,
            title: "Susun laporan pemakaian dashboard Q3",
            description: null,
            status: "approved",
            priority: null,
            displayOrder: 0,
            projectId,
            deadline: "2026-06-28T00:00:00.000Z",
            assigneeId: 3,
            createdBy: 1,
            isClaimable: false,
            createdAt: "2026-06-10T09:00:00.000Z",
            updatedAt: "2026-06-29T08:00:00.000Z",
        },
        {
            id: -109,
            title: "Migrasi database ke versi terbaru",
            description: "Ternyata butuh downtime, ditolak dan dijadwalkan ulang",
            status: "rejected",
            priority: 1,
            displayOrder: 1,
            projectId,
            deadline: "2026-07-15T00:00:00.000Z",
            assigneeId: 2,
            createdBy: 1,
            isClaimable: false,
            createdAt: "2026-07-01T09:00:00.000Z",
            updatedAt: "2026-07-14T09:00:00.000Z",
        },
    ];
}
