import { MyTask } from "@/types/task";

// Dummy sementara — hapus file ini begitu GET /task/me sudah tersedia di
// server, lalu ganti pemanggilan di page.tsx dari dummy ke getMyTasks().
export const dummyMyTasks: MyTask[] = [
    {
        id: -1,
        title: "Desain wireframe halaman login",
        description: "Buat wireframe low-fidelity untuk alur login & register",
        status: "ongoing",
        priority: 1,
        displayOrder: 0,
        projectId: -1,
        deadline: "2026-08-13T00:00:00.000Z",
        assigneeId: 1,
        createdBy: -1,
        isClaimable: false,
        createdAt: "2026-08-01T08:30:00.000Z",
        updatedAt: null,
        projectTitle: "Website Redesign",
    },
    {
        id: -2,
        title: "Setup CI/CD pipeline",
        description: null,
        status: "todo",
        priority: null,
        displayOrder: 1,
        projectId: -4,
        deadline: "2026-08-12T00:00:00.000Z",
        assigneeId: 1,
        createdBy: -10,
        isClaimable: false,
        createdAt: "2026-08-05T14:20:00.000Z",
        updatedAt: null,
        projectTitle: "API Migration to v2",
    },
    {
        id: -3,
        title: "Review PR integrasi payment gateway",
        description: null,
        status: "submitted",
        priority: 2,
        displayOrder: 2,
        projectId: -4,
        deadline: "2026-08-20T00:00:00.000Z",
        assigneeId: 1,
        createdBy: -10,
        isClaimable: false,
        createdAt: "2026-08-06T09:00:00.000Z",
        updatedAt: "2026-08-10T11:00:00.000Z",
        projectTitle: "API Migration to v2",
    },
    {
        id: -4,
        title: "Perbaiki bug validasi form onboarding",
        description: "User bisa lolos ke step 2 walau field wajib kosong",
        status: "in_revision",
        priority: 1,
        displayOrder: 0,
        projectId: -2,
        deadline: "2026-08-09T00:00:00.000Z",
        assigneeId: 1,
        createdBy: -4,
        isClaimable: false,
        createdAt: "2026-07-20T10:00:00.000Z",
        updatedAt: "2026-08-08T15:30:00.000Z",
        projectTitle: "Mobile App - Onboarding Flow",
    },
    {
        id: -5,
        title: "Susun laporan pemakaian dashboard Q3",
        description: null,
        status: "approved",
        priority: null,
        displayOrder: 3,
        projectId: -3,
        deadline: "2026-06-28T00:00:00.000Z",
        assigneeId: 1,
        createdBy: -6,
        isClaimable: false,
        createdAt: "2026-06-10T09:00:00.000Z",
        updatedAt: "2026-06-29T08:00:00.000Z",
        projectTitle: "Internal Tools - Reporting Dashboard",
    },
    {
        id: -6,
        title: "Tulis dokumentasi endpoint auth",
        description: null,
        status: "unclaimed",
        priority: null,
        displayOrder: 4,
        projectId: -4,
        deadline: null,
        assigneeId: null,
        createdBy: -10,
        isClaimable: true,
        createdAt: "2026-08-07T09:00:00.000Z",
        updatedAt: null,
        projectTitle: "API Migration to v2",
    },
];
